# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P:/ECP/Software/ecp_powersupply/ecp_ps_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1087, 693)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(60, 20, 471, 41))
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.tabMain = QtWidgets.QTabWidget(self.centralwidget)
        self.tabMain.setGeometry(QtCore.QRect(40, 80, 681, 531))
        self.tabMain.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabMain.setObjectName("tabMain")
        self.ps_test_tab = QtWidgets.QWidget()
        self.ps_test_tab.setObjectName("ps_test_tab")
        self.label_8 = QtWidgets.QLabel(self.ps_test_tab)
        self.label_8.setGeometry(QtCore.QRect(400, 280, 121, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.lbl5p0a = QtWidgets.QLabel(self.ps_test_tab)
        self.lbl5p0a.setGeometry(QtCore.QRect(260, 250, 81, 21))
        self.lbl5p0a.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lbl5p0a.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl5p0a.setLineWidth(3)
        self.lbl5p0a.setTextFormat(QtCore.Qt.PlainText)
        self.lbl5p0a.setObjectName("lbl5p0a")
        self.groupBox = QtWidgets.QGroupBox(self.ps_test_tab)
        self.groupBox.setGeometry(QtCore.QRect(40, 60, 321, 80))
        self.groupBox.setObjectName("groupBox")
        self.spinPriStartVolt = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinPriStartVolt.setGeometry(QtCore.QRect(10, 40, 91, 22))
        self.spinPriStartVolt.setMinimum(18.0)
        self.spinPriStartVolt.setMaximum(40.0)
        self.spinPriStartVolt.setSingleStep(0.025)
        self.spinPriStartVolt.setObjectName("spinPriStartVolt")
        self.spinPriEndVolt = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinPriEndVolt.setGeometry(QtCore.QRect(120, 40, 81, 22))
        self.spinPriEndVolt.setMinimum(18.0)
        self.spinPriEndVolt.setMaximum(40.0)
        self.spinPriEndVolt.setSingleStep(0.025)
        self.spinPriEndVolt.setProperty("value", 40.0)
        self.spinPriEndVolt.setObjectName("spinPriEndVolt")
        self.spinPriVoltInc = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinPriVoltInc.setGeometry(QtCore.QRect(220, 40, 71, 22))
        self.spinPriVoltInc.setMinimum(0.01)
        self.spinPriVoltInc.setMaximum(2.0)
        self.spinPriVoltInc.setProperty("value", 2.0)
        self.spinPriVoltInc.setObjectName("spinPriVoltInc")
        self.sblPriStartVolt_2 = QtWidgets.QLabel(self.groupBox)
        self.sblPriStartVolt_2.setGeometry(QtCore.QRect(120, 20, 91, 16))
        self.sblPriStartVolt_2.setObjectName("sblPriStartVolt_2")
        self.sblPriStartVolt_3 = QtWidgets.QLabel(self.groupBox)
        self.sblPriStartVolt_3.setGeometry(QtCore.QRect(220, 20, 71, 16))
        self.sblPriStartVolt_3.setObjectName("sblPriStartVolt_3")
        self.sblPriStartVolt_4 = QtWidgets.QLabel(self.groupBox)
        self.sblPriStartVolt_4.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.sblPriStartVolt_4.setObjectName("sblPriStartVolt_4")
        self.label_7 = QtWidgets.QLabel(self.ps_test_tab)
        self.label_7.setGeometry(QtCore.QRect(380, 250, 141, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.spinBox = QtWidgets.QSpinBox(self.ps_test_tab)
        self.spinBox.setGeometry(QtCore.QRect(400, 100, 91, 22))
        self.spinBox.setMinimum(50)
        self.spinBox.setMaximum(100)
        self.spinBox.setProperty("value", 90)
        self.spinBox.setObjectName("spinBox")
        self.label = QtWidgets.QLabel(self.ps_test_tab)
        self.label.setGeometry(QtCore.QRect(26, 220, 141, 20))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.ps_test_tab)
        self.label_6.setGeometry(QtCore.QRect(380, 220, 151, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.lbl12v = QtWidgets.QLabel(self.ps_test_tab)
        self.lbl12v.setGeometry(QtCore.QRect(170, 280, 81, 21))
        self.lbl12v.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lbl12v.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl12v.setLineWidth(3)
        self.lbl12v.setTextFormat(QtCore.Qt.PlainText)
        self.lbl12v.setObjectName("lbl12v")
        self.lbl12va = QtWidgets.QLabel(self.ps_test_tab)
        self.lbl12va.setGeometry(QtCore.QRect(260, 280, 81, 21))
        self.lbl12va.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lbl12va.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl12va.setLineWidth(3)
        self.lbl12va.setTextFormat(QtCore.Qt.PlainText)
        self.lbl12va.setObjectName("lbl12va")
        self.groupBox_2 = QtWidgets.QGroupBox(self.ps_test_tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 170, 351, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lblBias = QtWidgets.QLabel(self.ps_test_tab)
        self.lblBias.setGeometry(QtCore.QRect(540, 280, 81, 21))
        self.lblBias.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lblBias.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblBias.setLineWidth(3)
        self.lblBias.setTextFormat(QtCore.Qt.PlainText)
        self.lblBias.setObjectName("lblBias")
        self.sblPriStartVolt = QtWidgets.QLabel(self.ps_test_tab)
        self.sblPriStartVolt.setGeometry(QtCore.QRect(400, 80, 141, 16))
        self.sblPriStartVolt.setObjectName("sblPriStartVolt")
        self.lbl1p5v = QtWidgets.QLabel(self.ps_test_tab)
        self.lbl1p5v.setGeometry(QtCore.QRect(170, 190, 81, 21))
        self.lbl1p5v.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lbl1p5v.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl1p5v.setLineWidth(3)
        self.lbl1p5v.setTextFormat(QtCore.Qt.PlainText)
        self.lbl1p5v.setObjectName("lbl1p5v")
        self.lblEsa = QtWidgets.QLabel(self.ps_test_tab)
        self.lblEsa.setGeometry(QtCore.QRect(540, 250, 81, 21))
        self.lblEsa.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lblEsa.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblEsa.setLineWidth(3)
        self.lblEsa.setTextFormat(QtCore.Qt.PlainText)
        self.lblEsa.setObjectName("lblEsa")
        self.lbl5p0v = QtWidgets.QLabel(self.ps_test_tab)
        self.lbl5p0v.setGeometry(QtCore.QRect(170, 250, 81, 21))
        self.lbl5p0v.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lbl5p0v.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl5p0v.setLineWidth(3)
        self.lbl5p0v.setTextFormat(QtCore.Qt.PlainText)
        self.lbl5p0v.setObjectName("lbl5p0v")
        self.lbl3p3a = QtWidgets.QLabel(self.ps_test_tab)
        self.lbl3p3a.setGeometry(QtCore.QRect(260, 220, 81, 21))
        self.lbl3p3a.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lbl3p3a.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl3p3a.setLineWidth(3)
        self.lbl3p3a.setTextFormat(QtCore.Qt.PlainText)
        self.lbl3p3a.setObjectName("lbl3p3a")
        self.lbl1p5a = QtWidgets.QLabel(self.ps_test_tab)
        self.lbl1p5a.setGeometry(QtCore.QRect(260, 190, 81, 21))
        self.lbl1p5a.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lbl1p5a.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl1p5a.setLineWidth(3)
        self.lbl1p5a.setTextFormat(QtCore.Qt.PlainText)
        self.lbl1p5a.setObjectName("lbl1p5a")
        self.lblMcpPosOut = QtWidgets.QLabel(self.ps_test_tab)
        self.lblMcpPosOut.setGeometry(QtCore.QRect(540, 190, 81, 21))
        self.lblMcpPosOut.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lblMcpPosOut.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblMcpPosOut.setLineWidth(3)
        self.lblMcpPosOut.setTextFormat(QtCore.Qt.PlainText)
        self.lblMcpPosOut.setObjectName("lblMcpPosOut")
        self.label_4 = QtWidgets.QLabel(self.ps_test_tab)
        self.label_4.setGeometry(QtCore.QRect(26, 280, 141, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.lblMcpNegOut = QtWidgets.QLabel(self.ps_test_tab)
        self.lblMcpNegOut.setGeometry(QtCore.QRect(540, 220, 81, 21))
        self.lblMcpNegOut.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lblMcpNegOut.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblMcpNegOut.setLineWidth(3)
        self.lblMcpNegOut.setTextFormat(QtCore.Qt.PlainText)
        self.lblMcpNegOut.setObjectName("lblMcpNegOut")
        self.btnStartScan = QtWidgets.QPushButton(self.ps_test_tab)
        self.btnStartScan.setGeometry(QtCore.QRect(450, 350, 75, 23))
        self.btnStartScan.setObjectName("btnStartScan")
        self.lbl3p3v = QtWidgets.QLabel(self.ps_test_tab)
        self.lbl3p3v.setGeometry(QtCore.QRect(170, 220, 81, 21))
        self.lbl3p3v.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lbl3p3v.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl3p3v.setLineWidth(3)
        self.lbl3p3v.setTextFormat(QtCore.Qt.PlainText)
        self.lbl3p3v.setObjectName("lbl3p3v")
        self.label_5 = QtWidgets.QLabel(self.ps_test_tab)
        self.label_5.setGeometry(QtCore.QRect(380, 190, 151, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.ps_test_tab)
        self.label_2.setGeometry(QtCore.QRect(26, 190, 141, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.ps_test_tab)
        self.label_3.setGeometry(QtCore.QRect(26, 250, 141, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.tabMain.addTab(self.ps_test_tab, "")
        self.tabManualControl = QtWidgets.QWidget()
        self.tabManualControl.setObjectName("tabManualControl")
        self.btnSetPsVoltage = QtWidgets.QPushButton(self.tabManualControl)
        self.btnSetPsVoltage.setGeometry(QtCore.QRect(150, 50, 41, 23))
        self.btnSetPsVoltage.setObjectName("btnSetPsVoltage")
        self.spinPsVoltage = QtWidgets.QDoubleSpinBox(self.tabManualControl)
        self.spinPsVoltage.setGeometry(QtCore.QRect(50, 50, 91, 22))
        self.spinPsVoltage.setMinimum(18.0)
        self.spinPsVoltage.setMaximum(40.0)
        self.spinPsVoltage.setSingleStep(0.025)
        self.spinPsVoltage.setProperty("value", 18.0)
        self.spinPsVoltage.setObjectName("spinPsVoltage")
        self.label_10 = QtWidgets.QLabel(self.tabManualControl)
        self.label_10.setGeometry(QtCore.QRect(50, 30, 171, 16))
        self.label_10.setObjectName("label_10")
        self.radPSIn1Sel = QtWidgets.QRadioButton(self.tabManualControl)
        self.radPSIn1Sel.setGeometry(QtCore.QRect(50, 90, 82, 17))
        self.radPSIn1Sel.setAutoExclusive(False)
        self.radPSIn1Sel.setObjectName("radPSIn1Sel")
        self.radPSIn2Sel = QtWidgets.QRadioButton(self.tabManualControl)
        self.radPSIn2Sel.setGeometry(QtCore.QRect(50, 110, 82, 17))
        self.radPSIn2Sel.setAutoExclusive(False)
        self.radPSIn2Sel.setObjectName("radPSIn2Sel")
        self.tabMain.addTab(self.tabManualControl, "")
        self.addatest_tab = QtWidgets.QWidget()
        self.addatest_tab.setObjectName("addatest_tab")
        self.spinDacOut1 = QtWidgets.QDoubleSpinBox(self.addatest_tab)
        self.spinDacOut1.setGeometry(QtCore.QRect(80, 30, 91, 22))
        self.spinDacOut1.setMinimum(0.0)
        self.spinDacOut1.setMaximum(5.0)
        self.spinDacOut1.setSingleStep(0.025)
        self.spinDacOut1.setProperty("value", 0.0)
        self.spinDacOut1.setObjectName("spinDacOut1")
        self.btnSetDacOut1 = QtWidgets.QPushButton(self.addatest_tab)
        self.btnSetDacOut1.setGeometry(QtCore.QRect(180, 30, 75, 23))
        self.btnSetDacOut1.setObjectName("btnSetDacOut1")
        self.btnSetDacOut2 = QtWidgets.QPushButton(self.addatest_tab)
        self.btnSetDacOut2.setGeometry(QtCore.QRect(180, 60, 75, 23))
        self.btnSetDacOut2.setObjectName("btnSetDacOut2")
        self.spinDacOut2 = QtWidgets.QDoubleSpinBox(self.addatest_tab)
        self.spinDacOut2.setGeometry(QtCore.QRect(80, 60, 91, 22))
        self.spinDacOut2.setMinimum(0.0)
        self.spinDacOut2.setMaximum(5.0)
        self.spinDacOut2.setSingleStep(0.025)
        self.spinDacOut2.setProperty("value", 0.0)
        self.spinDacOut2.setObjectName("spinDacOut2")
        self.btnReadAdcRegister = QtWidgets.QPushButton(self.addatest_tab)
        self.btnReadAdcRegister.setGeometry(QtCore.QRect(510, 30, 121, 21))
        self.btnReadAdcRegister.setObjectName("btnReadAdcRegister")
        self.cboAdcRegisters = QtWidgets.QComboBox(self.addatest_tab)
        self.cboAdcRegisters.setGeometry(QtCore.QRect(330, 30, 171, 22))
        self.cboAdcRegisters.setObjectName("cboAdcRegisters")
        self.grpAdcs = QtWidgets.QGroupBox(self.addatest_tab)
        self.grpAdcs.setGeometry(QtCore.QRect(330, 70, 91, 191))
        self.grpAdcs.setCheckable(False)
        self.grpAdcs.setObjectName("grpAdcs")
        self.chkAdc1 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc1.setGeometry(QtCore.QRect(20, 20, 70, 17))
        self.chkAdc1.setObjectName("chkAdc1")
        self.chkAdc2 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc2.setGeometry(QtCore.QRect(20, 40, 70, 17))
        self.chkAdc2.setObjectName("chkAdc2")
        self.chkAdc3 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc3.setGeometry(QtCore.QRect(20, 60, 70, 17))
        self.chkAdc3.setObjectName("chkAdc3")
        self.chkAdc4 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc4.setGeometry(QtCore.QRect(20, 80, 71, 20))
        self.chkAdc4.setObjectName("chkAdc4")
        self.chkAdc8 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc8.setGeometry(QtCore.QRect(20, 160, 71, 20))
        self.chkAdc8.setObjectName("chkAdc8")
        self.chkAdc5 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc5.setGeometry(QtCore.QRect(20, 100, 70, 17))
        self.chkAdc5.setObjectName("chkAdc5")
        self.chkAdc7 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc7.setGeometry(QtCore.QRect(20, 140, 70, 17))
        self.chkAdc7.setObjectName("chkAdc7")
        self.chkAdc6 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc6.setGeometry(QtCore.QRect(20, 120, 70, 17))
        self.chkAdc6.setObjectName("chkAdc6")
        self.btnReadAdcs = QtWidgets.QPushButton(self.addatest_tab)
        self.btnReadAdcs.setGeometry(QtCore.QRect(340, 260, 81, 21))
        self.btnReadAdcs.setObjectName("btnReadAdcs")
        self.lblDac0 = QtWidgets.QLabel(self.addatest_tab)
        self.lblDac0.setGeometry(QtCore.QRect(40, 30, 31, 16))
        self.lblDac0.setObjectName("lblDac0")
        self.lblDac1 = QtWidgets.QLabel(self.addatest_tab)
        self.lblDac1.setGeometry(QtCore.QRect(40, 60, 31, 16))
        self.lblDac1.setObjectName("lblDac1")
        self.frame = QtWidgets.QFrame(self.addatest_tab)
        self.frame.setGeometry(QtCore.QRect(10, 10, 271, 471))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.spinDacOut1.raise_()
        self.btnSetDacOut1.raise_()
        self.btnSetDacOut2.raise_()
        self.spinDacOut2.raise_()
        self.btnReadAdcRegister.raise_()
        self.cboAdcRegisters.raise_()
        self.grpAdcs.raise_()
        self.btnReadAdcs.raise_()
        self.lblDac0.raise_()
        self.lblDac1.raise_()
        self.tabMain.addTab(self.addatest_tab, "")
        self.tabAddaConfig = QtWidgets.QWidget()
        self.tabAddaConfig.setObjectName("tabAddaConfig")
        self.spinSelAdcChan = QtWidgets.QSpinBox(self.tabAddaConfig)
        self.spinSelAdcChan.setGeometry(QtCore.QRect(140, 70, 61, 22))
        self.spinSelAdcChan.setMaximum(7)
        self.spinSelAdcChan.setObjectName("spinSelAdcChan")
        self.lblSelectAdcChan = QtWidgets.QLabel(self.tabAddaConfig)
        self.lblSelectAdcChan.setGeometry(QtCore.QRect(10, 70, 121, 20))
        self.lblSelectAdcChan.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSelectAdcChan.setObjectName("lblSelectAdcChan")
        self.cboAdcChGain = QtWidgets.QComboBox(self.tabAddaConfig)
        self.cboAdcChGain.setGeometry(QtCore.QRect(140, 100, 61, 22))
        self.cboAdcChGain.setObjectName("cboAdcChGain")
        self.cboAdcChGain.addItem("")
        self.cboAdcChGain.addItem("")
        self.cboAdcChGain.addItem("")
        self.cboAdcChGain.addItem("")
        self.cboAdcChGain.addItem("")
        self.cboAdcChGain.addItem("")
        self.cboAdcChGain.addItem("")
        self.lblSelecGain = QtWidgets.QLabel(self.tabAddaConfig)
        self.lblSelecGain.setGeometry(QtCore.QRect(10, 100, 121, 20))
        self.lblSelecGain.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSelecGain.setObjectName("lblSelecGain")
        self.lblSelMuxIn = QtWidgets.QLabel(self.tabAddaConfig)
        self.lblSelMuxIn.setGeometry(QtCore.QRect(80, 130, 141, 20))
        self.lblSelMuxIn.setObjectName("lblSelMuxIn")
        self.cboPosSel = QtWidgets.QComboBox(self.tabAddaConfig)
        self.cboPosSel.setGeometry(QtCore.QRect(130, 150, 69, 22))
        self.cboPosSel.setObjectName("cboPosSel")
        self.cboPosSel.addItem("")
        self.cboPosSel.addItem("")
        self.cboPosSel.addItem("")
        self.cboPosSel.addItem("")
        self.cboPosSel.addItem("")
        self.cboPosSel.addItem("")
        self.cboPosSel.addItem("")
        self.cboPosSel.addItem("")
        self.cboPosSel.addItem("")
        self.lblPsel = QtWidgets.QLabel(self.tabAddaConfig)
        self.lblPsel.setGeometry(QtCore.QRect(70, 150, 51, 20))
        self.lblPsel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPsel.setObjectName("lblPsel")
        self.cboNegSel = QtWidgets.QComboBox(self.tabAddaConfig)
        self.cboNegSel.setGeometry(QtCore.QRect(130, 180, 69, 22))
        self.cboNegSel.setObjectName("cboNegSel")
        self.cboNegSel.addItem("")
        self.cboNegSel.addItem("")
        self.cboNegSel.addItem("")
        self.cboNegSel.addItem("")
        self.cboNegSel.addItem("")
        self.cboNegSel.addItem("")
        self.cboNegSel.addItem("")
        self.cboNegSel.addItem("")
        self.cboNegSel.addItem("")
        self.lblNsel = QtWidgets.QLabel(self.tabAddaConfig)
        self.lblNsel.setGeometry(QtCore.QRect(70, 180, 51, 20))
        self.lblNsel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblNsel.setObjectName("lblNsel")
        self.btnStoreAdcChanConfig = QtWidgets.QPushButton(self.tabAddaConfig)
        self.btnStoreAdcChanConfig.setGeometry(QtCore.QRect(60, 210, 151, 23))
        self.btnStoreAdcChanConfig.setObjectName("btnStoreAdcChanConfig")
        self.tabMain.addTab(self.tabAddaConfig, "")
        self.tabDb = QtWidgets.QWidget()
        self.tabDb.setObjectName("tabDb")
        self.tableView = QtWidgets.QTableView(self.tabDb)
        self.tableView.setGeometry(QtCore.QRect(60, 60, 501, 411))
        self.tableView.setObjectName("tableView")
        self.cboDatabaseTableNames = QtWidgets.QComboBox(self.tabDb)
        self.cboDatabaseTableNames.setGeometry(QtCore.QRect(70, 20, 301, 22))
        self.cboDatabaseTableNames.setObjectName("cboDatabaseTableNames")
        self.tabMain.addTab(self.tabDb, "")
        self.txtDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.txtDisplay.setGeometry(QtCore.QRect(730, 100, 291, 511))
        self.txtDisplay.setObjectName("txtDisplay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1087, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabMain.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#aa0000;\">ECP Power Supply Testing</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>Bias Out Reading:</p></body></html>"))
        self.lbl5p0a.setText(_translate("MainWindow", ".51A"))
        self.groupBox.setTitle(_translate("MainWindow", "28V Primary Supply"))
        self.sblPriStartVolt_2.setText(_translate("MainWindow", "Ending Voltage"))
        self.sblPriStartVolt_3.setText(_translate("MainWindow", "Increment"))
        self.sblPriStartVolt_4.setText(_translate("MainWindow", "Starting Voltage"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>ESA Out Reading:</p></body></html>"))
        self.label.setText(_translate("MainWindow", "+3.3V Supply Reading:"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>MCP Neg Out Reading:</p></body></html>"))
        self.lbl12v.setText(_translate("MainWindow", "12.23V"))
        self.lbl12va.setText(_translate("MainWindow", ".12A"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Secondary Supplies"))
        self.lblBias.setText(_translate("MainWindow", "200V"))
        self.sblPriStartVolt.setText(_translate("MainWindow", "HV Clock Drive (KHz)"))
        self.lbl1p5v.setText(_translate("MainWindow", "1.50V"))
        self.lblEsa.setText(_translate("MainWindow", "300V"))
        self.lbl5p0v.setText(_translate("MainWindow", "4.95V"))
        self.lbl3p3a.setText(_translate("MainWindow", "1.32A"))
        self.lbl1p5a.setText(_translate("MainWindow", "0.05A"))
        self.lblMcpPosOut.setText(_translate("MainWindow", "200V"))
        self.label_4.setText(_translate("MainWindow", "+12V Supply Reading:"))
        self.lblMcpNegOut.setText(_translate("MainWindow", "3500V"))
        self.btnStartScan.setText(_translate("MainWindow", "Start Test"))
        self.lbl3p3v.setText(_translate("MainWindow", "3.31V"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>MCP Pos Out Reading:</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "+1.5V Supply Reading:"))
        self.label_3.setText(_translate("MainWindow", "+5V Supply Reading:"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.ps_test_tab), _translate("MainWindow", "PS Test"))
        self.btnSetPsVoltage.setText(_translate("MainWindow", "Set"))
        self.label_10.setText(_translate("MainWindow", "ECP PS VOLT IN (18 to 40V)"))
        self.radPSIn1Sel.setText(_translate("MainWindow", "PS Input 1"))
        self.radPSIn2Sel.setText(_translate("MainWindow", "PS Input 2"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabManualControl), _translate("MainWindow", "Manual Control"))
        self.btnSetDacOut1.setText(_translate("MainWindow", "Set"))
        self.btnSetDacOut2.setText(_translate("MainWindow", "Set"))
        self.btnReadAdcRegister.setText(_translate("MainWindow", "Read ADC Register"))
        self.grpAdcs.setTitle(_translate("MainWindow", "Select ADCs"))
        self.chkAdc1.setText(_translate("MainWindow", "ADC 1"))
        self.chkAdc2.setText(_translate("MainWindow", "ADC 2"))
        self.chkAdc3.setText(_translate("MainWindow", "ADC 3"))
        self.chkAdc4.setText(_translate("MainWindow", "ADC 4"))
        self.chkAdc8.setText(_translate("MainWindow", "ADC 8"))
        self.chkAdc5.setText(_translate("MainWindow", "ADC 5"))
        self.chkAdc7.setText(_translate("MainWindow", "ADC 7"))
        self.chkAdc6.setText(_translate("MainWindow", "ADC 6"))
        self.btnReadAdcs.setText(_translate("MainWindow", "Read ADCs"))
        self.lblDac0.setText(_translate("MainWindow", "DAC0"))
        self.lblDac1.setText(_translate("MainWindow", "DAC1"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.addatest_tab), _translate("MainWindow", "AD/DA Test"))
        self.lblSelectAdcChan.setText(_translate("MainWindow", "Select ADC Chan"))
        self.cboAdcChGain.setItemText(0, _translate("MainWindow", "Gain = 1"))
        self.cboAdcChGain.setItemText(1, _translate("MainWindow", "Gain = 2"))
        self.cboAdcChGain.setItemText(2, _translate("MainWindow", "Gain = 4"))
        self.cboAdcChGain.setItemText(3, _translate("MainWindow", "Gain = 8"))
        self.cboAdcChGain.setItemText(4, _translate("MainWindow", "Gain = 16"))
        self.cboAdcChGain.setItemText(5, _translate("MainWindow", "Gain = 32"))
        self.cboAdcChGain.setItemText(6, _translate("MainWindow", "Gain = 64"))
        self.lblSelecGain.setText(_translate("MainWindow", "Select Chan Gain"))
        self.lblSelMuxIn.setText(_translate("MainWindow", "Select Chan Inputs"))
        self.cboPosSel.setItemText(0, _translate("MainWindow", "AIN0"))
        self.cboPosSel.setItemText(1, _translate("MainWindow", "AIN1"))
        self.cboPosSel.setItemText(2, _translate("MainWindow", "AIN2"))
        self.cboPosSel.setItemText(3, _translate("MainWindow", "AIN3"))
        self.cboPosSel.setItemText(4, _translate("MainWindow", "AIN4"))
        self.cboPosSel.setItemText(5, _translate("MainWindow", "AIN5"))
        self.cboPosSel.setItemText(6, _translate("MainWindow", "AIN6"))
        self.cboPosSel.setItemText(7, _translate("MainWindow", "AIN7"))
        self.cboPosSel.setItemText(8, _translate("MainWindow", "AINCOM"))
        self.lblPsel.setText(_translate("MainWindow", "Pos In"))
        self.cboNegSel.setItemText(0, _translate("MainWindow", "AIN0"))
        self.cboNegSel.setItemText(1, _translate("MainWindow", "AIN1"))
        self.cboNegSel.setItemText(2, _translate("MainWindow", "AIN2"))
        self.cboNegSel.setItemText(3, _translate("MainWindow", "AIN3"))
        self.cboNegSel.setItemText(4, _translate("MainWindow", "AIN4"))
        self.cboNegSel.setItemText(5, _translate("MainWindow", "AIN5"))
        self.cboNegSel.setItemText(6, _translate("MainWindow", "AIN6"))
        self.cboNegSel.setItemText(7, _translate("MainWindow", "AIN7"))
        self.cboNegSel.setItemText(8, _translate("MainWindow", "AINCOM"))
        self.lblNsel.setText(_translate("MainWindow", "Neg In"))
        self.btnStoreAdcChanConfig.setText(_translate("MainWindow", "Submit"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabAddaConfig), _translate("MainWindow", "AD/DA Config"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabDb), _translate("MainWindow", "Database"))

